---
- name: Find current ami template id
  ec2_ami_find:
    region: "{{ region }}"
    name: "{{ ami_template_name }}"
    sort: creationDate
    sort_order: descending
    sort_end: 1
  register: ami_find

- name: Launch instance
  ec2:
    wait: yes
    instance_tags:
      Nagios: ignore
      Name: ansible-build-image
    group_id: "{{ group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami_find.results[0].ami_id }}"
    region: "{{ region }}"
    vpc_subnet_id: "{{ image_building_subnet_id }}"
  register: ec2

- debug:
    msg: "{{ ec2.instances.0.id }}"

- debug:
    msg: "{{ ec2.instances.0.private_ip }}"

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.private_ip }}"
    groupname: "{{ ansible_group_name }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.private_ip }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
