---
- name: get asg set_fact
  ec2_asg_facts:
    name: "{{ asg_name }}"
  register: asgs

- set_fact:
    new_lc_name: "{{ lc_name_prefix }}-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}"

- name: create launch config
  ec2_lc:
    name: "{{ new_lc_name }}"
    image_id: "{{ image.image_id }}"
    region: "{{ region }}"
    security_groups: "{{ service_sg_ids }}"
    instance_type: "{{ instance_type }}"

- debug:
    msg: "instance number in the group: {{ asgs.results[0].instances|length }}"

# for instance number more than 1 in the group, rolling update works as follows:
# loop:
#   shut down 1 instance, then create 1 new instance
# till all old instances are replaced
- include_tasks: rolling_update.yml
  when:
    - method == "rolling_update" 
    - asgs.results[0].instances|length > 1

- include_tasks: rolling_update_only_one_instance_in_the_group.yml
  when:
    - method == "rolling_update" 
    - asgs.results[0].instances|length == 1

- include_tasks: shutdown_first.yml
  when:
    - method == "shutdown_first"
