---
- name: rolling update asg
  ec2_asg:
    name: "{{ asg_name }}"
    launch_config_name: "{{ new_lc_name }}"
    replace_all_instances: yes
    min_size: "{{ asg_min_size }}" 
    max_size: "{{ asg_max_size }}"
    desired_capacity: "{{ asg_desired_capacity }}"
    region: "{{ region }}"
    vpc_zone_identifier: "{{ ms_subnet_id }}"
    tags:
      - Name: "{{ name_tag }}"
        propagate_at_launch: yes